### ISSUE TITLE
[BUG] Theme not applied in New Window

### ISSUE THREAD

**Issue by jshoaf** [Carbonateb/obsidian-encore-theme#12]
**Describe the Bug**
Theme is not applied when opening a note in a new window using Microsoft Windows app.  Using "Atom (One Dark)" in Dark Mode.

**Relevant Screenshots**

**To Reproduce**
Steps to reproduce the behavior, e.g.
- Right click on a new note and choose "Open in new Window"
- Observe theme is not applied.  This is observed by noticing header color is wrong.

**In which mode does the bug occur?**
- [ x ] Reading/Preview Mode
- [ x ] Source Mode
- [ x ] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [ x ] New Editor

**Which version of Obsidian are you using?**
- [ x ] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [ x ] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`). (using 2.3.4)
- [ x ] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme. (I understand this occurs in some themes, depending on how coded, but not all)

**Comment by Carbonateb** [comment]
I honestly have no clue how to style new windows, it's bugging me too :(

**Comment by Carbonateb** [comment]
This has been fixed in 2.8.2 via #21
