### ISSUE TITLE
When used together with the kanban plugin, the header bar hides some information

### ISSUE THREAD

**Issue by matheus-de-araujo** [Carbonateb/obsidian-encore-theme#13]
The header bar is hiding the title of each kanban column
![image](https://user-images.githubusercontent.com/69010160/228977460-3d5307b2-e5de-4d06-b601-50fdd81c1373.png)

**In which mode does the bug occur?**
- [ ] Reading/Preview Mode
- [ ] Source Mode
- [ ] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by matheus-de-araujo** [comment]
Adding the following code resolved the issue:
``` css
.view-header {
  position: relative !important;
}
```

**Comment by matheus-de-araujo** [comment]
I created a pull request to resolve this issue

**Comment by Carbonateb** [comment]
Thanks! I've merged the fix, it'll go live in the next update

**Comment by matheus-de-araujo** [comment]
Thank you very much
This project is amazing 👏🏻
