### ISSUE TITLE
[BUG] Transluent background not working on Linux

### ISSUE THREAD

**Issue by difhel** [Carbonateb/obsidian-encore-theme#23]
**Describe the Bug**
Translucent background seems to be not working in Linux. A "grainy" black background is displayed instead.

**Relevant Screenshots**

![image](https://github.com/Carbonateb/obsidian-encore-theme/assets/78644136/c3341af2-8f12-4eae-94fa-01639181c491)

**To Reproduce**
1. Download .deb release from https://obsidian.md
2. Create if you didn't and open your vault.
3. Go to Settings -> Appearance -> Themes -> Manage -> Search for "Encore" and install it.
4. Switch your theme to "Encore".

**In which mode does the bug occur?**
The bug appears on all application screens in Linux. On Windows with similar settings everything works fine.

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

Thanks for the great theme. Hopefully we can get this to work on Linux.

**Comment by Carbonateb** [comment]
Unfortunately, translucent window is not supported at all on Linux :(
Nothing I can do to fix it on my end, this is a limitation of Obsidian/Electron

Perhaps instead I can make a new option where you can set your own background image that gets blurred, to get a vaguely similar effect. Do you think this is something you might use instead?

**Comment by difhel** [comment]
Thanks for your reaction. It's a shame that there is such a limitation in Electron.

But I like your idea of choosing a background and applying the effect to it.  I will wait for its implementation. Thanks again for your work!

**Comment by Carbonateb** [comment]
Well, Obsidian just removed translucent support on Windows, so now it affects a lot of users...
I'll think of something.

**Comment by Carbonateb** [comment]
Check out the latest version, I have added this feature :)
