### ISSUE TITLE
[BUG] New table update (1.5) looses focus when typing

### ISSUE THREAD

**Issue by raphaelluethy** [Carbonateb/obsidian-encore-theme#24]
**Describe the Bug**
When having encore enabled, whenever I type using the new table editor, the cursor looses focus on the cell. I need to click in the cell after typing one character

**Relevant Screenshots**
https://share.cleanshot.com/DmrFWLdG

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. Click into table cell
2. type
3. click out of cell
4. see text appear (or it will overflow if you typed enough characters)

**In which mode does the bug occur?**
- [ ] Reading/Preview Mode
- [ ] Source Mode
- [ x ] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [ x ] New Editor

**Which version of Obsidian are you using?**
- [ ] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ x ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [ x ] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [ x ] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by Carbonateb** [comment]
Thanks for the report! I've fixed it in 2.8.3 which just went live
