### ISSUE TITLE
text doesnt show up correctly in grid cells in the new built-in table feature (v1.5.3)

### ISSUE THREAD

**Issue by eiliatmr** [Carbonateb/obsidian-encore-theme#25]
**Describe the Bug**
text doesnt show the first written words correctly till you write something long.
or drag/highlight the text with your cursor.

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. insert a new table
2. type in a grid cell

**In which mode does the bug occur?**
- [ ] Reading/Preview Mode
- [X] Source Mode
- [ ] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [X] New Editor

**Which version of Obsidian are you using?**
- [X] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [X] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [X] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by aquatix** [comment]
This also happens for me in Live Preview mode. Thanks for working on it!

**Comment by Carbonateb** [comment]
Thanks for the report! I've fixed it in 2.8.3 which just went live
