### ISSUE TITLE
[BUG] Table cells/rows grow in height when clicked on

### ISSUE THREAD

**Issue by CyclopeanCompact** [Carbonateb/obsidian-encore-theme#26]
**Describe the Bug**
Whenever I click on a table cell while using Encore, the row abruptly expands to four or five times the cell's original height; simultaneously, this seems to be treated by Obsidian as an attempt to position the caret at the very end of the afflicted line, so it means it is impossible to select a line of text in a table in one held click since it moves the caret to the wrong position.

I thought it'd be fixed with the patch that fixed the last issue with the new tables, but no such luck.

**Relevant Screenshots**

![image](https://github.com/Carbonateb/obsidian-encore-theme/assets/118838250/233db500-ba76-4694-ada0-31bf14ab4ca7)
![image](https://github.com/Carbonateb/obsidian-encore-theme/assets/118838250/94e10458-52cd-4d06-8dec-a15cc77114ca)

**To Reproduce**

1. Create a table of any size or shape.
2. Click on any row.

**In which mode does the bug occur?**
- [ ] Reading/Preview Mode
- [ ] Source Mode
- [X] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [X] New Editor

**Which version of Obsidian are you using?**
- [X] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [X] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [X] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by Carbonateb** [comment]
hmm I wasn't able to reproduce the issue on my end

![image](https://github.com/Carbonateb/obsidian-encore-theme/assets/31268463/489f59b8-4967-4dd3-8570-0e4798ca22b1)

it could be a weird edge case between some of your plugins and Encore, maybe try opening a new vault and gradually adding back plugins until the issue occurs?

**Comment by CyclopeanCompact** [comment]
So after seeing a fresh drive with Encore and nothing else installed worked, I did some further A/B testing, systemically stripping out every part of my `.obsidian` folder. I eventually determined that Style Settings appeared to somehow be the root of the problem, but after installing it on a new vault, it appeared to work fine. The *actual* problem is Encore's Fancy View Headers. Enabling this setting under Style Settings is what causes the awkward table issues. I had it enabled on my original personal vault, but it isn't enabled by default, so the new vault didn't experience the problem until I toggled it on.

**Comment by Carbonateb** [comment]
Ah, great job finding the cause of the issue!
I was able to reproduce it on my end, and have issued a fix :)

Thanks for the report ❤️

Yeah I disabled fancy headers by default due to the number of issues it causes with plugins and such, I'd prefer new users to have a more polished albeit less fancy experience by default.
