### ISSUE TITLE
[BUG] Italics are highlighted in bolded italics while in live preview mode instead of simply italics

### ISSUE THREAD

**Issue by CyclopeanCompact** [Carbonateb/obsidian-encore-theme#27]
**Describe the Bug**
Italics are rendered in both bold and italics instead of simply italics in the live preview mode.

**Relevant Screenshots**

![image](https://github.com/Carbonateb/obsidian-encore-theme/assets/118838250/89607ae2-8176-4c29-b411-b01190a52b4b)

**To Reproduce**
1. Set any text in the editor to be rendered in italics using asterisks as per standard Markdown.
2. Examine the text's weight.

**In which mode does the bug occur?**
- [ ] Reading/Preview Mode
- [ ] Source Mode
- [x] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by Carbonateb** [comment]
This has been fixed in 2.8.5 :)
