### ISSUE TITLE
Feature Request: Disable highlight border toggle

### ISSUE THREAD

**Issue by CyclopeanCompact** [Carbonateb/obsidian-encore-theme#28]
**Feature Requested**
I would appreciate a toggle that disables the bright border around the theme's highlighting to be disabled, leaving the highlight as a simple ambient glow around highlighted text. I find the outline distracting, especially when multiple lines are highlighted at once (as the border does not merge vertically when several lines of text are highlighted; it can add a lot of visual noise) and it is not a regular feature of the highlight in most themes, so I figure it might have wider use outside of my own CSS snippet ... and it would prevent me from having to maintain a separate CSS snippet.

**Relevant Screenshots**

![image](https://github.com/Carbonateb/obsidian-encore-theme/assets/118838250/84461293-dfcf-4036-9564-4aec8f51c3b3)

![image](https://github.com/Carbonateb/obsidian-encore-theme/assets/118838250/22f4b956-0326-47f0-9ad5-666696d85d6a)

**Checklist**
- [x] The feature would be useful to more users than just me. (→ If it's only relevant to you, have you considered using a [CSS Snippet](https://help.obsidian.md/How+to/Add+custom+styles.md#Use+Themes+and/or+CSS+snippets)?)

**Comment by Carbonateb** [comment]
I agree, the highlight style falls apart in most situations tbh, anytime it's not just a single bit of text highlighted.
Check out the latest version, I've made it look a lot cleaner!
