### ISSUE TITLE
Feature Request: Add an option to toggle old embedded note style

### ISSUE THREAD

**Issue by ImaginaryProgramming** [Carbonateb/obsidian-encore-theme#9]
**Feature Requested**
I'd like an option in Style Settings to re-enable the old style used on embedded notes. I personally prefer it to the new one.

**Relevant Screenshots**
Old style:
![image](https://user-images.githubusercontent.com/92801558/216168141-d2f6317d-80ed-4e08-9418-afcccc039a16.png)

New style:
![image](https://user-images.githubusercontent.com/92801558/216168180-1a227093-b6a9-4af5-a576-47774cab49e9.png)

**Checklist**
- [x] The feature would be useful to more users than just me. (My coworker and I both really liked the old style)

**Comment by Carbonateb** [comment]
Mega late but I've gone back and redone embedded notes to be similar to how they used to be:
![image](https://github.com/Carbonateb/obsidian-encore-theme/assets/31268463/5af4e357-1280-40c7-9376-9eadc00e935c)

If you're curious - I never intended to change it, I just forgot to do it when rewriting the theme for Obsidian's new default theme.

Hope you enjoy!
